version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - myapp-network

  backend:
    build: ./backend
    image: golang-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=cakap
      - DB_PASSWORD=cakap123
      - DB_NAME=book_store
      - DATABASE_USER=cakap
      - DATABASE_PASSWORD=cakap123
      - DATABASE_DATABASE=book_store
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - PORT=8080
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - db
    networks:
      - myapp-network

  db:
    image: mysql:5.7
    container_name: db_container
    environment:
      - MYSQL_ROOT_PASSWORD=cakap234
      - MYSQL_DATABASE=book_store
      - MYSQL_USER=cakap
      - MYSQL_PASSWORD=cakap123
    networks:
      - myapp-network
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  migration:
    build:
      context: ./backend
      dockerfile: ./build/migrate.dockerfile
    container_name: migration_container
    environment:
      - DATABASE_URL=mysql://cakap:cakap123@tcp(db:3306)/book_store?parseTime=true
    command: ["-verbose", "up"]
    depends_on:
      - db
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge

volumes:
  db-data: